### ISSUE TITLE
Bug in html template literal

### ISSUE THREAD

**Issue by shaunlebron** [asg017/dataflow#24]
Strings interpolated inside an html template literal are not treated as html:

```js
html`<span>${`<b>hello</b>`}</span>`
```

expected result: **hello**
actual result: `<b>hello</b>`

You can verify the expected result in an Observable cell.

My actual use case was to build an html table with rows like:

```js
html`
<table>
${rows.map(({a,b}) => `<tr><td>${a}</td><td>${b}</td></tr>`).join('\n')}
</table>
`
```

**Comment by asg017** [comment]
Hey @shaunlebron !

Dataflow uses [htl](https://github.com/observablehq/htl) for the `html` and `svg` builtin cells, so the syntax and usage is slightly different than the old `html` builtin that's currently used on observablehq.com.

So your `<b>Hello</b>` example is expected behavior. However, to fix your table example, you can do something like this:


```javascript
rows = [{a: 1, b: 2}, {a:3, b:4}, {a:5, b:6}]

html`
<table>
  ${rows.map(({a,b}) => html`<tr><td>${a}</td><td>${b}</td></tr>`)}
</table>
`
```

<image width=200 src="https://user-images.githubusercontent.com/15178711/119022078-0c05d680-b955-11eb-8259-3279c6442941.png"/>

Here, we can return an array of HTML elements (by using `html` again inside the map function), and htl [will expand it](https://github.com/observablehq/htl#iterable-values) (so no need to `.join()` the final result!).

Also, not sure what you're using the table for, but wanted to point out the [Inputs](https://github.com/observablehq/inputs) library that is available as the builtin cell `Inputs`, and more specifically [Inputs.table](https://github.com/observablehq/inputs#Table) for tables
